### ISSUE TITLE
GPU out of memory

### ISSUE THREAD

**Issue by CVMI2019** [priba/siamese_ged#1]
We train the model ( train_siamese_net.py ) on the HistoGraph dataset with default parameters, however the it is crashed with out of memory. Our GPU is 1080ti with 12G memory.  
What is the parameter you used? and how long it takes for training ?

**Comment by priba** [comment]
We train it with a GPU TITAN Xp. Have you tried to reduce the batch size? It takes quite a lot for training, around 2 days.
