### ISSUE TITLE
RuntimeError: The expanded size of the tensor (1) must match the existing size (64) at non-singleton dimension 0

### ISSUE THREAD

**Issue by walexi** [priba/siamese_ged#2]
I'm trying to run the code in the repository and have been running into a number of issues.
Please find below my environment configuration and snapshots of the error.

![error4](https://user-images.githubusercontent.com/3662231/58179661-8d5ffb00-7ca0-11e9-89e3-df5db3b195b5.PNG)

![error3](https://user-images.githubusercontent.com/3662231/58179912-08291600-7ca1-11e9-8f17-8fe845e9c26b.PNG)

**Comment by priba** [comment]
I updated the requirements.txt with the pytorch version used in this project
